### ISSUE TITLE
TestADE extension do not export geometry

### ISSUE THREAD

**Issue by matteomandrile** [3dcitydb/extension-test-ade#2]
Hello, 
I am following the [ADE Manager Plugin Documentation](https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/impexp/plugins/ade-manager.html#ade-manager-plugin-registration-chapter) to extend my 3dcitydb. I was successful in the registration and transformation of the `testADE`as per image below
<img src="https://user-images.githubusercontent.com/8726351/91642574-bdae5180-ea2c-11ea-9d16-ab6c91fdc5a1.png" width="70%"/>

inspecting the DB with pgAdmin confirm also that the operation was successful:
<img src="https://user-images.githubusercontent.com/8726351/91642610-0c5beb80-ea2d-11ea-8385-69a0baf9a381.png" width="30%"/>

I was also able to extend the Import/Export Tool and import the 2 sample datsets
<img src="https://user-images.githubusercontent.com/8726351/91642551-8344b480-ea2c-11ea-8f1c-ef074c93c127.png" width="70%"/>
<img src="https://user-images.githubusercontent.com/8726351/91642694-b2a7f100-ea2d-11ea-8bb1-a9940889e06a.png" width="30%"/>

However, when I export the sample dataset and inspect it with both FME data inspector and FZKViewer I don't see **any geometry or content**
<img src="https://user-images.githubusercontent.com/8726351/91643233-aaea4b80-ea31-11ea-8221-326ad8f09969.png" width="70%"/>
<img src="https://user-images.githubusercontent.com/8726351/91642967-bfc5df80-ea2f-11ea-9f4c-b8088233b5e1.png" width="100%"/>

in FME I get the following warning:
> Parsing XML document 'C:\Users\MatteoMandrile\Desktop\ade test.gml'
> <xfMap> -  registered 1 messages of type:  XML element 'test:IndustrialBuilding' and its content might be skipped - 'http://www.citygml.org/ade/TestADE/1.0' namespace is not recognized in XML doc 'C:\Users\MatteoMandrile\Desktop\ade test.gml' 
> <xfMap> -  registered 580 messages of type:  XML element 'test:OtherConstruction' and its content might be skipped - 'http://www.citygml.org/ade/TestADE/1.0' namespace is not recognized in XML doc 'C:\Users\MatteoMandrile\Desktop\ade test.gml' 

Can you help me with this?

**Comment by yaozhihang** [comment]
OK, I can reproduce this problem. The cause is that the schema location of the TestADE is missing in the exported CityGML document. That's why the FME cannot parse and read the CityGML file. 

A quick fix is to manually add the ADE schema location information to `xsi:schemaLocation` in the CityGML file. The ADE XML Schema can be found here
https://github.com/3dcitydb/extension-test-ade/tree/master/resources/schema

Here is an example. 
[tesade_examplet.zip](https://github.com/3dcitydb/extension-test-ade/files/5146961/tesade_examplet.zip)

**Comment by ufalakbar** [comment]
I following 3dcitydb ADE Manager from importer/exporter v.4.2.0. but when I register my ADE there is a warning like this: 

The following CityGML ADEs are registered in the database but are not supported:
RBI3DADE 1.0

I think the problem is in the jar file in the lib folder. when I use the compiled jar of your ADE extension namely test-ade-citydb-1.2.0.jar and test-ade-citygml4j-1.2.0.jar, it doesn't work. but when I use the jar downloaded from websites 3dcitydb.org, then ADE works. How can I use the jar that I build or compile by myself?
