### ISSUE TITLE
Only Last Node of the first Level of ADE is imported/shown in List

### ISSUE THREAD

**Issue by e3DChristoph** [3dcitydb/extension-test-ade#5]
Hey,

![image](https://user-images.githubusercontent.com/23355799/192250512-9c09f5ad-89a1-40da-af60-cd480554b715.png)
As seen in the picture, when importing the EnergyADE 1.0 from KIT, only the Weatherstation is available after the import, while there should be more Nodes to see.

Maybe this should be an Issue for the Importer/Exporter and not the ADE Extension. If so please let me know so I can move it.

Thanks

**Comment by clausnagel** [comment]
Wow, no answer in almost 3 years. Sorry for that.

This not an issue but expected behavior. The import, export, and delete operations of the Importer/Exporter only operate on top-level features but not on nested sub-features. This is why the feature type filter only contains top-level features. This is also documented in the [3DCityDB online manual](http://3dcitydb-docs.rtfd.io/).
